### ISSUE TITLE
Dependent variable in DNN model

### ISSUE THREAD

**Issue by sophia-wright-blue** [GoogleCloudPlatform/tensorflow-lifetime-value#2]
thanks for releasing this repo - what is the dependent variable in the DNN model?

I get that in the probability model, the inputs are the RFM attributes, and the CLV is calculated from the RFM values, but I'm trying to understand how to create a dependent variable from the transaction data, so that the DNN model can train the weights of the network;

I'd greatly appreciate a response, thanks

**Comment by m-mayran** [comment]
The target is the monetary value.

**Comment by sophia-wright-blue** [comment]
thanks for that info, @m-mayran ,
